name: Expo Update on Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  expo_build:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ› ï¸ Setup repo
        uses: actions/checkout@v2

      - name: ðŸ› ï¸ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn

      - name: ðŸ› ï¸ Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ðŸ“¦ Install dependencies
        run: yarn install

      - name: ðŸ—¿ Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto

 

      # - name: Install dependencies
      #   run: yarn install

      # - name: Install EAS Updates & CLI
      #   run: npx expo install expo-updates && npm install --global eas-cli

      # - name: Build apk
      #   run: eas build --profile preview --platform android --non-interactive

      # - name: Get QR Code URL
      #   id: get_qr_code_url
      #   run: echo "::set-output name=url::$(npx expo url:apk)"

      # - name: Post QR Code
      #   uses: unsplash/comment-on-pr@master
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.MY_GIT_TOKEN }}
      #     msg: >
      #       You can preview the PR by scanning the QR code below: <br />
      #       <img src="${{ steps.get_qr_code_url.outputs.url }}" height="256" width="256">

#github - https://github.com/expo/expo-preview-action#create-a-qr-code-under-pull-request

# - name: Publish to Expo & create a QR code
#   uses: expo/expo-preview-action@v1
#   with:
#     channel: pr-${{ github.event.number }}
#   id: preview
